### ISSUE TITLE
Some misc ideas

### ISSUE THREAD

**Issue by mslxl** [JadMax/JadMax.github.io#1]
Hello, long time no see, it is so happy that you are using github, here are some ideas on your repo.
* If you make your `.unitypackage` file public, why do not you create a repo to manage your code, use git to manage is handy, also others can reference your code conveniently. I think is better than use Baidu Netdisk.
* I found that you give up the Hexo and switch to Jekyll, I do not know why but I guess because GitHub does not support Hexo server, but I have got a solution on how to build Hexo Page, you can use [travis.yml](https://github.com/mslxl/mslxl.github.io/blob/source/.travis.yml) to config TravisCI, then build this page on CI.If I am wrong, ignore it.

These are my suggestions on your project.
If you are against me, you can close this issue.

**Comment by JadMax** [comment]
- Actually I'm not gonna work on unitypackages so often, so I think just putting it(them) on Baidu ND is a better choice for me myself; (ummmm, well to be honest, Git is the very thing I'm not so familiar with, period. Ps: sad thing ain't it?)
- About the 'blog' thing, the truth is I'm too lazy to set up ~~a~~ another blog. So I made a backup of my former website-like 'blog' and set up a blank repo, (as what I've mentioned that I'm lazy) then I simply wrote index.md (yeah, a cannot-be-any-simpler markdown file) to be my 'blog', using the default settings provided by Github.
- All in all, the problems are caused by my laziness.
(ENGLISH CONVERSATION IS SO ~~EXOTIC~~STRANGE...)

**Comment by mslxl** [comment]
Well, I expect your game that you wrote.

Besides, should I delete your URL from my blog's [link page](https://blog.mslxl.com/links/)?

(About English conversation, I think is  necessary to use English to communication on the foreign community, though my English is poor.)



------------------ 原始邮件 ------------------
发件人: "aBelongsToA"<notifications@github.com>; 
发送时间: 2019年8月21日(星期三) 下午3:57
收件人: "JadMax/JadMax.github.io"<JadMax.github.io@noreply.github.com>; 
抄送: "mslxl"<1302485739@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [JadMax/JadMax.github.io] Some misc ideas (#1)



 
Actually I'm not gonna work on unitypackages so often, so I think just putting it(them) on Baidu ND is a better choice for me myself; (ummmm, well to be honest, Git is the very thing I'm not so familiar with, period. Ps: sad thing ain't it?)
 
About the 'blog' thing, the truth is I'm too lazy to set up a another blog. So I made a backup of my former website-like 'blog' and set up a blank repo, (as what I've mentioned that I'm lazy) then I simply wrote index.md (yeah, a cannot-be-any-simpler markdown file) to be my 'blog', using the default settings provided by Github.
 
All in all, the problems are caused by my laziness.
 (ENGLISH CONVERSATION IS SO EXOTICSTRANGE...)
